const CodeToCountry = {
    USD: "دلار آمریکا",
    EUR: "یورو",
    GBP : "پوند انگلیس",
    CHF : "پوند بریتانیا",
    CAD : "دلار کانادا",
    AUD : "دلار استرالیا",
    SEK : "کرون سوئد",
    NOK : "کرون نروژ",
    RUB : "روبل روسیه",
    THB : "بات تایلند",
    SGD : "دلار سنگاپور",
    HKD : "دلار هنگ کنگ",
    AZN : "منات آذربایجان",
    AMD : "درام ارمنستان",
    DKK : "کرون دانمارک",
    AED : "درهم امارات",
    JPY : "ین ژاپن",
    TRY : "لیر ترکیه",
    CNY : "یوان چین",
    SAR : "ریال عربستان",
    INR : "روپیه هند",
    MYR : "رینگیت مالزی",
    AFN : "افغانی",
    KWD : "دینار کویت",
    IQD : "دینار عراق",
    BHD : "دینار بحرین",
    OMR : "ریال عمان",
    QAR : "ریال قطر",
}

const CodeToFlag = {
    USD: "us",
    EUR : "us",
    GBP : "us",
    CHF : "us",
    CAD : "us",
    AUD : "us",
    SEK : "us",
    NOK : "us",
    RUB : "us",
    THB : "us",
    SGD : "us",
    HKD : "us",
    AZN : "us",
    AMD : "us",
    DKK : "us",
    AED : "us",
    JPY : "us",
    TRY : "us",
    CNY : "us",
    SAR : "us",
    INR : "us",
    MYR : "us",
    AFN : "us",
    KWD : "us",
    IQD : "us",
    BHD : "us",
    OMR : "us",
    QAR : "us",
    '1 Old Azadi' : "us",
    '1 Emami' : "us",
    '1/2 Azadi' : "us",
    '1/4 Azadi' : "us",
}

const PersianGoldName =  {
    '1 Old Azadi' : "سکه بهار آزادی",
    '1 Emami' : "سکه امامی",
    '1/2 Azadi' : "نیم سکه آزادی",
    '1/4 Azadi' : "ربع سکه بهار آزادی",
}

export {
    CodeToCountry,
    CodeToFlag,
    PersianGoldName
};
