const CodeToCountry = {
    USD: "دلار آمریکا",
    EUR: "یورو",
    GBP : "پوند انگلیس",
    CHF : "پوند بریتانیا",
    CAD : "دلار کانادا",
    AUD : "دلار استرالیا",
    SEK : "کرون سوئد",
    NOK : "کرون نروژ",
    RUB : "روبل روسیه",
    THB : "بات تایلند",
    SGD : "دلار سنگاپور",
    HKD : "دلار هنگ کنگ",
    AZN : "منات آذربایجان",
    AMD : "درام ارمنستان",
    DKK : "کرون دانمارک",
    AED : "درهم امارات",
    JPY : "ین ژاپن",
    TRY : "لیر ترکیه",
    CNY : "یوان چین",
    SAR : "ریال عربستان",
    INR : "روپیه هند",
    MYR : "رینگیت مالزی",
    AFN : "افغانی",
    KWD : "دینار کویت",
    IQD : "دینار عراق",
    BHD : "دینار بحرین",
    OMR : "ریال عمان",
    QAR : "ریال قطر",
}

const CodeToFlag = {
    USD: "us",
    EUR : "eur",
    GBP : "gbp",
    CHF : "chf",
    CAD : "cad",
    AUD : "aud",
    SEK : "sek",
    NOK : "nok",
    RUB : "rub",
    THB : "thb",
    SGD : "sgd",
    HKD : "hkd",
    AZN : "azn",
    AMD : "amd",
    DKK : "dkk",
    AED : "aed",
    JPY : "jpy",
    TRY : "try",
    CNY : "cny",
    SAR : "sar",
    INR : "inr",
    MYR : "myr",
    AFN : "afn",
    KWD : "kwd",
    IQD : "iqd",
    BHD : "bhd",
    OMR : "omr",
    QAR : "qar",
    '1 Old Azadi' : "1oldazadi",
    '1 Emami' : "1oldazadi",
    '1/2 Azadi' : "1oldazadi",
    '1/4 Azadi' : "1oldazadi",
    'Ounce' : "ounce",
    'Mithqal' : "ounce",
    "Gold 18" : "ounce",
    "Bitcoin" : "bitcoin",
    "Bourse" : "bourse"
}

const PersianGoldName =  {
    '1 Old Azadi' : "سکه بهار آزادی",
    '1 Emami' : "سکه امامی",
    '1/2 Azadi' : "نیم سکه آزادی",
    '1/4 Azadi' : "ربع سکه بهار آزادی",
    'Ounce' : "انس",
    'Mithqal' : "مثقال",
    "Gold 18" : "طلای ۱۸ عیار",
    "Bitcoin" : "بیت کوین",
    "Bourse" : "بورس"
}

export {
    CodeToCountry,
    CodeToFlag,
    PersianGoldName
};
